### ISSUE TITLE
Can't build driver when FEATURE_COMMON_PAL is missing - no mention of this in the docs

### ISSUE THREAD

**Issue by iriark01** [ARMmbed/atmel-rf-driver#38]
FEATURE_COMMON_PAL needs to be in mbed_app.json, otherwise on build you get the error "fatal error: platform/arm_hal_interrupt.h:".

Can you add this to the docs? I couldn't find mention of it.

Please talk to @janjongboom if you need more information about the build error.

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-2750

**Comment by hasnainvirk** [comment]
FEATURE_COMMON_PAL is an mbedOS-5 module whereas atmel-rf-driver is a generic module used by various flavours of mbedOS.
There is no co-dependency between these two modules. While using mbedOS-5, its application's job to include FEATURE_COMMON_PAL, actually IMO its a mandatory inclusion
as it contains common platform abstractions used by all the network stack variations we support. The application mbed_app.json must include it in target_overrides.

**Comment by janjongboom** [comment]
I disagree. If we know that this library will be built using Makefile's will we also not include those, because maybe someone wants to compile by hand?! We should make it *easy* to use our libraries. And that means that adding a library to an mbed OS program (both which come from the very same business unit) should be one single line: `mbed add whatever`. Not: one single line and then adding a completely undocumented feature thing line in some json file.

@hasnainvirk

**Comment by hasnainvirk** [comment]
@janjongboom Russ is working on that. Currently there is a solution at least for mbedOS. However, to sync the driver with bare-meta nanostack is not so trivial. Please give us a little time. Brainstorming is already going on :)

**Comment by janjongboom** [comment]
Plus we already have an mbed_lib.json here :p

**Comment by SeppoTakalo** [comment]
Fixed in #61
